# Generated by Django 2.2.6 on 2019-10-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrack', '0003_auto_20191024_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprintBacklog',
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='status',
            field=models.CharField(default='current', max_length=200),
        ),
        migrations.CreateModel(
            name='SprintBacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('pointEstimate', models.IntegerField()),
                ('sprintBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrack.SprintBacklog')),
            ],
        ),
    ]
